version: 2

sources:
  - name: raw_nyc_tripdata
    database: agile-athlete-449216-m2
    schema: ny_taxi
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_2019_hw4
      - name: zones 